tracing:
    zipkin:
        http:
            url: http://localhost:9411
        enabled: true
        sampler:
            probability: 1
---
kafka:
    #  embedded:
    #    enabled: true
    bootstrap:
        servers: "${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}"